name: Build Kivy APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip git zip unzip openjdk-8-jdk
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.19 virtualenv
        
    - name: Set up Android SDK and NDK
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        
        # Install Android SDK
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d cmdline-tools
        mkdir -p android-sdk/cmdline-tools/latest
        mv cmdline-tools/* android-sdk/cmdline-tools/latest/
        rm -rf cmdline-tools cmdline-tools.zip
        
        echo "ANDROID_SDK_ROOT=$GITHUB_WORKSPACE/android-sdk" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
        
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-29" "build-tools;30.0.3"
        
        # Install NDK
        wget https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip -O ndk.zip
        unzip ndk.zip
        rm ndk.zip
        
        echo "ANDROID_NDK_HOME=$GITHUB_WORKSPACE/android-ndk-r19c" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/android-ndk-r19c:$PATH" >> $GITHUB_ENV
    
    - name: Install Python packages
      run: |
        pip install kivy pygame mutagen
        
    - name: Create buildozer.spec
      run: |
        cat <<EOF > buildozer.spec
        [app]
        title = Music Player
        package.name = musicplayer
        package.domain = org.example
        source.dir = .
        source.include_exts = py,png,jpg,kv,mp3
        version = 0.1
        requirements = python3,kivy,pygame,mutagen
        android.permissions = INTERNET
        android.api = 29
        android.minapi = 21
        android.ndk_path = $GITHUB_WORKSPACE/android-ndk-r19c
        android.sdk_path = $GITHUB_WORKSPACE/android-sdk
        android.arch = armeabi-v7a
        p4a.branch = master
        orientation = portrait
        fullscreen = 0
        log_level = 2
        EOF
    
    - name: Build APK
      run: |
        export PATH=$PATH:$GITHUB_WORKSPACE/android-sdk/platform-tools
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v3.1.3
      with:
        name: music-player-apk
        path: bin/*.apk
