name: Build Kivy APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip git zip unzip openjdk-8-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.19 virtualenv
        
    - name: Set up Android SDK
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        
        # Download and install Android Command Line Tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d cmdline-tools
        mkdir -p android-sdk/cmdline-tools/latest
        mv cmdline-tools/* android-sdk/cmdline-tools/latest/
        rm -rf cmdline-tools cmdline-tools.zip
        
        # Set environment variables
        echo "ANDROID_SDK_ROOT=$GITHUB_WORKSPACE/android-sdk" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
        
        # Accept licenses and install required components
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-29" "build-tools;30.0.3" "patcher;v4" "emulator"
        
    - name: Set up Android NDK
      run: |
        # Download and install NDK r19c
        wget https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip -O ndk.zip
        unzip ndk.zip
        rm ndk.zip
        
        echo "ANDROID_NDK_HOME=$GITHUB_WORKSPACE/android-ndk-r19c" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/android-ndk-r19c:$PATH" >> $GITHUB_ENV
    
    - name: Install Python dependencies
      run: |
        pip install kivy==2.0.0 pygame==2.0.1 mutagen==1.45.1
        
    - name: Create buildozer.spec
      run: |
        echo "[app]" > buildozer.spec
        echo "title = Music Player" >> buildozer.spec
        echo "package.name = musicplayer" >> buildozer.spec
        echo "package.domain = org.example" >> buildozer.spec
        echo "source.dir = ." >> buildozer.spec
        echo "source.include_exts = py,png,jpg,kv,mp3" >> buildozer.spec
        echo "version = 0.1" >> buildozer.spec
        echo "requirements = python3,kivy==2.0.0,pygame==2.0.1,mutagen==1.45.1" >> buildozer.spec
        echo "android.permissions = INTERNET" >> buildozer.spec
        echo "android.api = 29" >> buildozer.spec
        echo "android.minapi = 21" >> buildozer.spec
        echo "android.ndk_path = $GITHUB_WORKSPACE/android-ndk-r19c" >> buildozer.spec
        echo "android.sdk_path = $GITHUB_WORKSPACE/android-sdk" >> buildozer.spec
        echo "android.arch = armeabi-v7a" >> buildozer.spec
        echo "p4a.branch = master" >> buildozer.spec
        echo "orientation = portrait" >> buildozer.spec
        echo "fullscreen = 0" >> buildozer.spec
        echo "log_level = 2" >> buildozer.spec
    
    - name: Build APK with Buildozer
      run: |
        export PATH=$PATH:$GITHUB_WORKSPACE/android-sdk/platform-tools
        buildozer -v android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: music-player-apk
        path: bin/*.apk
